export const Types = {
  FETCH_PRODUCTS : "FETCH_PRODUCTS", 
  SELECTED_PRODUCT : "SELECTED_PRODUCT",
  FETCH_CATEGORIES : "FETCH_CATEGORIES",
  FILTER_CATEGORY : "FILTER_CATEGORY",
  FILTER_PRICE : "FILTER_PRICE",
  FILTER_SORT : "FILTER_SORT",
  ADD_CART : "ADD_CART",
  REMOVE_CART : "REMOVE_CART",
  REMOVE_ALL_PRODUCTS : "REMOVE_ALL_PRODUCTS",
}